name: CD # Continuous Deployment

on:
  push:
    tags:
      - '[v]?[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.platform.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Build binary
      uses: houseabsolute/actions-rust-cross@9ea5352c0f279f0b89ea2eb503337acf4f27c73e # v0
      with:
        command: build
        target: ${{ matrix.platform.target }}
        args: "--locked --release"
        strip: true
    - name: Publish artifacts and release
      uses: houseabsolute/actions-rust-release@e47c661840f938dcc4587f52ef780bf05b1e1381 # v0
      with:
        executable-name: mado
        target: ${{ matrix.platform.target }}
        changes-file: CHANGELOG.md
