name: CI Action # Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Use local action
        uses: ./
