name: CI # Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@8ac6587749dbe3babc697a844a5e5053fde90c5a # 1.84.0
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Run tests
        run: cargo test --all-features --workspace
        env:
          CLICOLOR_FORCE: true
          TZ: 'Asia/Tokyo'

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@8ac6587749dbe3babc697a844a5e5053fde90c5a # 1.84.0
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@8ac6587749dbe3babc697a844a5e5053fde90c5a # 1.84.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@8ac6587749dbe3babc697a844a5e5053fde90c5a # 1.84.0
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --all-features --workspace

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@8ac6587749dbe3babc697a844a5e5053fde90c5a # 1.84.0
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@eba66cc6f87204a1e73f96e528e759b6c1fcf573 # cargo-llvm-cov
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        env:
          CLICOLOR_FORCE: true
          TZ: 'Asia/Tokyo'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
