name: Taplo

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  taplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: uncenter/setup-taplo@b18c8c8302695fe63d6853bc004006215ac52b91 # v2
        with:
          version: "0.9.3"
      - name: Run Taplo
        run: taplo format --check
