name: Typos

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: crate-ci/typos@9d890159570d5018df91fedfa40b4730cd4a81b1 # v1.28.4
